apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  namespace: staging
spec:
  replicas: 2  # Scalability: 2 pods
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      imagePullSecrets:
      - name: dockerhub-cred 
      containers:
      - name: demo-app
        image: madhavsurajyashaswini298/demo-app:latest  # Updated after pushing
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        readinessProbe:  # Ensures new pods are healthy before serving
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
            requests:
              cpu:    "100m"     # Pod will get at least 100 millicpu (~0.1 CPU)
              memory: "128Mi"    # Pod will get at least 128 MiB RAM
            limits:
              cpu:    "500m"     # Pod can burst up to 0.5 CPU
              memory: "512Mi" 
