apiVersion: v1
kind: Service
metadata:
  name: demo-app-service
spec:
  type: ClusterIP   
  selector:
    app: demo-app  # Matches pod labels for auto-discovery
  ports:
    - port: 80       # ALB routes to this
      targetPort: 3000  # Demo app's container port
